//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace AutoCoE.Extensibility.Plugins.DataModel
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum autocoe_DesktopFlowDLPImpactProfileState
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum autocoe_desktopflowdlpimpactprofile_statuscode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }

    /// <summary>
    /// 
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("autocoe_desktopflowdlpimpactprofile")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public partial class autocoe_DesktopFlowDLPImpactProfile : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {

        /// <summary>
        /// Default Constructor.
        /// </summary>
        public autocoe_DesktopFlowDLPImpactProfile() :
                base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "autocoe_desktopflowdlpimpactprofile";

        public const string EntityLogicalCollectionName = "autocoe_desktopflowdlpimpactprofiles";

        public const string EntitySetName = "autocoe_desktopflowdlpimpactprofiles";

        public const int EntityTypeCode = 10191;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_actionname")]
        public string autocoe_ActionName
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_actionname");
            }
            set
            {
                this.OnPropertyChanging("autocoe_ActionName");
                this.SetAttributeValue("autocoe_actionname", value);
                this.OnPropertyChanged("autocoe_ActionName");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_actionrecordid")]
        public string autocoe_ActionRecordId
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_actionrecordid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_ActionRecordId");
                this.SetAttributeValue("autocoe_actionrecordid", value);
                this.OnPropertyChanged("autocoe_ActionRecordId");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowdefinition")]
        public Microsoft.Xrm.Sdk.EntityReference autocoe_DesktopFlowDefinition
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("autocoe_desktopflowdefinition");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowDefinition");
                this.SetAttributeValue("autocoe_desktopflowdefinition", value);
                this.OnPropertyChanged("autocoe_DesktopFlowDefinition");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowdlpimpactprofileid")]
        public System.Nullable<System.Guid> autocoe_DesktopFlowDLPImpactProfileId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("autocoe_desktopflowdlpimpactprofileid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowDLPImpactProfileId");
                this.SetAttributeValue("autocoe_desktopflowdlpimpactprofileid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("autocoe_DesktopFlowDLPImpactProfileId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowdlpimpactprofileid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.autocoe_DesktopFlowDLPImpactProfileId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowid")]
        public string autocoe_DesktopFlowId
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_desktopflowid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowId");
                this.SetAttributeValue("autocoe_desktopflowid", value);
                this.OnPropertyChanged("autocoe_DesktopFlowId");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowname")]
        public string autocoe_DesktopFlowName
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_desktopflowname");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowName");
                this.SetAttributeValue("autocoe_desktopflowname", value);
                this.OnPropertyChanged("autocoe_DesktopFlowName");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_environmentid")]
        public string autocoe_EnvironmentId
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_environmentid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_EnvironmentId");
                this.SetAttributeValue("autocoe_environmentid", value);
                this.OnPropertyChanged("autocoe_EnvironmentId");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_modulename")]
        public string autocoe_ModuleName
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_modulename");
            }
            set
            {
                this.OnPropertyChanging("autocoe_ModuleName");
                this.SetAttributeValue("autocoe_modulename", value);
                this.OnPropertyChanged("autocoe_ModuleName");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_modulesource")]
        public string autocoe_ModuleSource
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_modulesource");
            }
            set
            {
                this.OnPropertyChanging("autocoe_ModuleSource");
                this.SetAttributeValue("autocoe_modulesource", value);
                this.OnPropertyChanged("autocoe_ModuleSource");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_occurrencecount")]
        public System.Nullable<int> autocoe_OccurrenceCount
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("autocoe_occurrencecount");
            }
            set
            {
                this.OnPropertyChanging("autocoe_OccurrenceCount");
                this.SetAttributeValue("autocoe_occurrencecount", value);
                this.OnPropertyChanged("autocoe_OccurrenceCount");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_selectorid")]
        public string autocoe_SelectorId
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_selectorid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_SelectorId");
                this.SetAttributeValue("autocoe_selectorid", value);
                this.OnPropertyChanged("autocoe_SelectorId");
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.OnPropertyChanging("OverriddenCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }
            set
            {
                this.OnPropertyChanging("OwnerId");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the Desktop Flow DLP Impact Profile
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.autocoe_DesktopFlowDLPImpactProfileState> statecode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.autocoe_DesktopFlowDLPImpactProfileState)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.autocoe_DesktopFlowDLPImpactProfileState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("statecode");
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Reason for the status of the Desktop Flow DLP Impact Profile
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.autocoe_desktopflowdlpimpactprofile_statuscode> statuscode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.autocoe_desktopflowdlpimpactprofile_statuscode)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.autocoe_desktopflowdlpimpactprofile_statuscode), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("statuscode");
                if ((value == null))
                {
                    this.SetAttributeValue("statuscode", null);
                }
                else
                {
                    this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("statuscode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.OnPropertyChanging("TimeZoneRuleVersionNumber");
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.OnPropertyChanging("UTCConversionTimeZoneCode");
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }
    }
}
