//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace AutoCoE.Extensibility.Plugins.DataModel
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum workflow_businessprocesstype
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessFlow = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaskFlow = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum workflow_category
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Workflow = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dialog = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessRule = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Action = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessProcessFlow = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ModernFlow = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DesktopFlow = 6,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum workflow_mode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Background = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Realtime = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum processtrigger_scope
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Form = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Entity = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum workflow_scope
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessUnit = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentChildBusinessUnits = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organization = 4,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum WorkflowState
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activated = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspended = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum workflow_statuscode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activated = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyDLPViolation = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum workflow_type
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Definition = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activation = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Template = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum workflow_uiflowtype
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        WindowsrecorderV1 = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SeleniumIDE = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PowerAutomateDesktop = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Recording = 101,
    }

    /// <summary>
    /// Set of logical rules that define the steps necessary to automate a specific business process, task, or set of actions to be performed.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("workflow")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public partial class Workflow : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {

        /// <summary>
        /// Default Constructor.
        /// </summary>
        public Workflow() :
                base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "workflow";

        public const string EntityLogicalCollectionName = "workflows";

        public const string EntitySetName = "workflows";

        public const int EntityTypeCode = 4703;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the latest activation record for the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activeworkflowid")]
        public Microsoft.Xrm.Sdk.EntityReference ActiveWorkflowId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("activeworkflowid");
            }
        }

        /// <summary>
        /// Indicates whether the asynchronous system job is automatically deleted on completion.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("asyncautodelete")]
        public System.Nullable<bool> AsyncAutoDelete
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("asyncautodelete");
            }
            set
            {
                this.OnPropertyChanging("AsyncAutoDelete");
                this.SetAttributeValue("asyncautodelete", value);
                this.OnPropertyChanged("AsyncAutoDelete");
            }
        }

        /// <summary>
        /// Business Process Type.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessprocesstype")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.workflow_businessprocesstype> BusinessProcessType
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("businessprocesstype");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.workflow_businessprocesstype)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.workflow_businessprocesstype), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("BusinessProcessType");
                if ((value == null))
                {
                    this.SetAttributeValue("businessprocesstype", null);
                }
                else
                {
                    this.SetAttributeValue("businessprocesstype", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("BusinessProcessType");
            }
        }

        /// <summary>
        /// Category of the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("category")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.workflow_category> Category
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("category");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.workflow_category)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.workflow_category), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("Category");
                if ((value == null))
                {
                    this.SetAttributeValue("category", null);
                }
                else
                {
                    this.SetAttributeValue("category", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("Category");
            }
        }

        /// <summary>
        /// Business logic converted into client data
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clientdata")]
        public string ClientData
        {
            get
            {
                return this.GetAttributeValue<string>("clientdata");
            }
            set
            {
                this.OnPropertyChanging("ClientData");
                this.SetAttributeValue("clientdata", value);
                this.OnPropertyChanged("ClientData");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
        public Microsoft.Xrm.Sdk.OptionSetValue ComponentState
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("componentstate");
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the process was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Stage of the process when triggered on Create.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createstage")]
        public Microsoft.Xrm.Sdk.OptionSetValue CreateStage
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("createstage");
            }
            set
            {
                this.OnPropertyChanging("CreateStage");
                this.SetAttributeValue("createstage", value);
                this.OnPropertyChanged("CreateStage");
            }
        }

        /// <summary>
        /// Stage of the process when triggered on Delete.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("deletestage")]
        public Microsoft.Xrm.Sdk.OptionSetValue DeleteStage
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("deletestage");
            }
            set
            {
                this.OnPropertyChanging("DeleteStage");
                this.SetAttributeValue("deletestage", value);
                this.OnPropertyChanged("DeleteStage");
            }
        }

        /// <summary>
        /// Description of the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
        public string Description
        {
            get
            {
                return this.GetAttributeValue<string>("description");
            }
            set
            {
                this.OnPropertyChanging("Description");
                this.SetAttributeValue("description", value);
                this.OnPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Shows the default image for the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
        public byte[] EntityImage
        {
            get
            {
                return this.GetAttributeValue<byte[]>("entityimage");
            }
            set
            {
                this.OnPropertyChanging("EntityImage");
                this.SetAttributeValue("entityimage", value);
                this.OnPropertyChanged("EntityImage");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
        public System.Nullable<long> EntityImage_Timestamp
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
        public string EntityImage_URL
        {
            get
            {
                return this.GetAttributeValue<string>("entityimage_url");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
        public System.Nullable<System.Guid> EntityImageId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
            }
        }

        /// <summary>
        /// Unique identifier of the associated form.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("formid")]
        public System.Nullable<System.Guid> FormId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("formid");
            }
            set
            {
                this.OnPropertyChanging("FormId");
                this.SetAttributeValue("formid", value);
                this.OnPropertyChanged("FormId");
            }
        }

        /// <summary>
        /// Input parameters to the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("inputparameters")]
        public string InputParameters
        {
            get
            {
                return this.GetAttributeValue<string>("inputparameters");
            }
            set
            {
                this.OnPropertyChanging("InputParameters");
                this.SetAttributeValue("inputparameters", value);
                this.OnPropertyChanged("InputParameters");
            }
        }

        /// <summary>
        /// Version in which the form is introduced.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("introducedversion")]
        public string IntroducedVersion
        {
            get
            {
                return this.GetAttributeValue<string>("introducedversion");
            }
            set
            {
                this.OnPropertyChanging("IntroducedVersion");
                this.SetAttributeValue("introducedversion", value);
                this.OnPropertyChanged("IntroducedVersion");
            }
        }

        /// <summary>
        /// Indicates whether the process was created using the Microsoft Dynamics 365 Web application.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscrmuiworkflow")]
        public System.Nullable<bool> IsCrmUIWorkflow
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("iscrmuiworkflow");
            }
        }

        /// <summary>
        /// Information that specifies whether this component can be customized.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
        public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
            }
            set
            {
                this.OnPropertyChanging("IsCustomizable");
                this.SetAttributeValue("iscustomizable", value);
                this.OnPropertyChanged("IsCustomizable");
            }
        }

        /// <summary>
        /// Defines whether other publishers can attach custom processing steps to this action
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomprocessingstepallowedforotherpublishers")]
        public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomProcessingStepAllowedForOtherPublishers
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomprocessingstepallowedforotherpublishers");
            }
            set
            {
                this.OnPropertyChanging("IsCustomProcessingStepAllowedForOtherPublishers");
                this.SetAttributeValue("iscustomprocessingstepallowedforotherpublishers", value);
                this.OnPropertyChanged("IsCustomProcessingStepAllowedForOtherPublishers");
            }
        }

        /// <summary>
        /// Indicates whether the solution component is part of a managed solution.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
        public System.Nullable<bool> IsManaged
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
            }
        }

        /// <summary>
        /// Whether or not the steps in the process are executed in a single transaction.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("istransacted")]
        public System.Nullable<bool> IsTransacted
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("istransacted");
            }
            set
            {
                this.OnPropertyChanging("IsTransacted");
                this.SetAttributeValue("istransacted", value);
                this.OnPropertyChanged("IsTransacted");
            }
        }

        /// <summary>
        /// Language of the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("languagecode")]
        public System.Nullable<int> LanguageCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("languagecode");
            }
            set
            {
                this.OnPropertyChanging("LanguageCode");
                this.SetAttributeValue("languagecode", value);
                this.OnPropertyChanged("LanguageCode");
            }
        }

        /// <summary>
        /// Shows the mode of the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mode")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.workflow_mode> Mode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mode");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.workflow_mode)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.workflow_mode), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("Mode");
                if ((value == null))
                {
                    this.SetAttributeValue("mode", null);
                }
                else
                {
                    this.SetAttributeValue("mode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("Mode");
            }
        }

        /// <summary>
        /// Unique identifier of the user who last modified the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the process was last modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who last modified the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Name of the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
        public string Name
        {
            get
            {
                return this.GetAttributeValue<string>("name");
            }
            set
            {
                this.OnPropertyChanging("Name");
                this.SetAttributeValue("name", value);
                this.OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Indicates whether the process is able to run as an on-demand process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ondemand")]
        public System.Nullable<bool> OnDemand
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("ondemand");
            }
            set
            {
                this.OnPropertyChanging("OnDemand");
                this.SetAttributeValue("ondemand", value);
                this.OnPropertyChanged("OnDemand");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
        public System.Nullable<System.DateTime> OverwriteTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
            }
        }

        /// <summary>
        /// Unique identifier of the user or team who owns the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }
            set
            {
                this.OnPropertyChanging("OwnerId");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier of the business unit that owns the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier of the team who owns the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier of the user who owns the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Unique identifier of the definition for process activation.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentworkflowid")]
        public Microsoft.Xrm.Sdk.EntityReference ParentWorkflowId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentworkflowid");
            }
        }

        /// <summary>
        /// Unique identifier of the plug-in type.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("plugintypeid")]
        public Microsoft.Xrm.Sdk.EntityReference PluginTypeId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("plugintypeid");
            }
        }

        /// <summary>
        /// Primary entity for the process. The process can be associated for one or more SDK operations defined on the primary entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryentity")]
        public string PrimaryEntity
        {
            get
            {
                return this.GetAttributeValue<string>("primaryentity");
            }
            set
            {
                this.OnPropertyChanging("PrimaryEntity");
                this.SetAttributeValue("primaryentity", value);
                this.OnPropertyChanged("PrimaryEntity");
            }
        }

        /// <summary>
        /// Type the business process flow order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processorder")]
        public System.Nullable<int> ProcessOrder
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("processorder");
            }
            set
            {
                this.OnPropertyChanging("ProcessOrder");
                this.SetAttributeValue("processorder", value);
                this.OnPropertyChanged("ProcessOrder");
            }
        }

        /// <summary>
        /// Contains the role assignment for the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processroleassignment")]
        public string ProcessRoleAssignment
        {
            get
            {
                return this.GetAttributeValue<string>("processroleassignment");
            }
            set
            {
                this.OnPropertyChanging("ProcessRoleAssignment");
                this.SetAttributeValue("processroleassignment", value);
                this.OnPropertyChanged("ProcessRoleAssignment");
            }
        }

        /// <summary>
        /// Unique identifier of the associated form for process trigger.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processtriggerformid")]
        public System.Nullable<System.Guid> ProcessTriggerFormId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("processtriggerformid");
            }
            set
            {
                this.OnPropertyChanging("ProcessTriggerFormId");
                this.SetAttributeValue("processtriggerformid", value);
                this.OnPropertyChanged("ProcessTriggerFormId");
            }
        }

        /// <summary>
        /// Scope of the process trigger.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processtriggerscope")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.processtrigger_scope> ProcessTriggerScope
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("processtriggerscope");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.processtrigger_scope)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.processtrigger_scope), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("ProcessTriggerScope");
                if ((value == null))
                {
                    this.SetAttributeValue("processtriggerscope", null);
                }
                else
                {
                    this.SetAttributeValue("processtriggerscope", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("ProcessTriggerScope");
            }
        }

        /// <summary>
        /// Indicates the rank for order of execution for the synchronous workflow.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rank")]
        public System.Nullable<int> Rank
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("rank");
            }
            set
            {
                this.OnPropertyChanging("Rank");
                this.SetAttributeValue("rank", value);
                this.OnPropertyChanged("Rank");
            }
        }

        /// <summary>
        /// The renderer type of Workflow
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rendererobjecttypecode")]
        public string RendererObjectTypeCode
        {
            get
            {
                return this.GetAttributeValue<string>("rendererobjecttypecode");
            }
            set
            {
                this.OnPropertyChanging("RendererObjectTypeCode");
                this.SetAttributeValue("rendererobjecttypecode", value);
                this.OnPropertyChanged("RendererObjectTypeCode");
            }
        }

        /// <summary>
        /// Specifies the system user account under which a workflow executes.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runas")]
        public Microsoft.Xrm.Sdk.OptionSetValue RunAs
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("runas");
            }
            set
            {
                this.OnPropertyChanging("RunAs");
                this.SetAttributeValue("runas", value);
                this.OnPropertyChanged("RunAs");
            }
        }

        /// <summary>
        /// Scope of the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("scope")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.workflow_scope> Scope
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("scope");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.workflow_scope)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.workflow_scope), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("Scope");
                if ((value == null))
                {
                    this.SetAttributeValue("scope", null);
                }
                else
                {
                    this.SetAttributeValue("scope", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("Scope");
            }
        }

        /// <summary>
        /// Unique identifier of the SDK Message associated with this workflow.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdkmessageid")]
        public Microsoft.Xrm.Sdk.EntityReference SdkMessageId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdkmessageid");
            }
        }

        /// <summary>
        /// Unique identifier of the associated solution.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
        public System.Nullable<System.Guid> SolutionId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
            }
        }

        /// <summary>
        /// Status of the workflow
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.WorkflowState> StateCode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.WorkflowState)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.WorkflowState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("StateCode");
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("StateCode");
            }
        }

        /// <summary>
        /// Reason for the status of the workflow
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.workflow_statuscode> StatusCode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.workflow_statuscode)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.workflow_statuscode), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("StatusCode");
                if ((value == null))
                {
                    this.SetAttributeValue("statuscode", null);
                }
                else
                {
                    this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("StatusCode");
            }
        }

        /// <summary>
        /// Indicates whether the process can be included in other processes as a child process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subprocess")]
        public System.Nullable<bool> Subprocess
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("subprocess");
            }
            set
            {
                this.OnPropertyChanging("Subprocess");
                this.SetAttributeValue("subprocess", value);
                this.OnPropertyChanged("Subprocess");
            }
        }

        /// <summary>
        /// Select whether synchronous workflow failures will be saved to log files.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("syncworkflowlogonfailure")]
        public System.Nullable<bool> SyncWorkflowLogOnFailure
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("syncworkflowlogonfailure");
            }
            set
            {
                this.OnPropertyChanging("SyncWorkflowLogOnFailure");
                this.SetAttributeValue("syncworkflowlogonfailure", value);
                this.OnPropertyChanged("SyncWorkflowLogOnFailure");
            }
        }

        /// <summary>
        /// Indicates whether the process will be triggered when the primary entity is created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggeroncreate")]
        public System.Nullable<bool> TriggerOnCreate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("triggeroncreate");
            }
            set
            {
                this.OnPropertyChanging("TriggerOnCreate");
                this.SetAttributeValue("triggeroncreate", value);
                this.OnPropertyChanged("TriggerOnCreate");
            }
        }

        /// <summary>
        /// Indicates whether the process will be triggered on deletion of the primary entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggerondelete")]
        public System.Nullable<bool> TriggerOnDelete
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("triggerondelete");
            }
            set
            {
                this.OnPropertyChanging("TriggerOnDelete");
                this.SetAttributeValue("triggerondelete", value);
                this.OnPropertyChanged("TriggerOnDelete");
            }
        }

        /// <summary>
        /// Attributes that trigger the process when updated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggeronupdateattributelist")]
        public string TriggerOnUpdateAttributeList
        {
            get
            {
                return this.GetAttributeValue<string>("triggeronupdateattributelist");
            }
            set
            {
                this.OnPropertyChanging("TriggerOnUpdateAttributeList");
                this.SetAttributeValue("triggeronupdateattributelist", value);
                this.OnPropertyChanged("TriggerOnUpdateAttributeList");
            }
        }

        /// <summary>
        /// For Internal Use Only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trustedaccess")]
        public System.Nullable<bool> TrustedAccess
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("trustedaccess");
            }
        }

        /// <summary>
        /// Type of the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("type")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.workflow_type> Type
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("type");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.workflow_type)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.workflow_type), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("Type");
                if ((value == null))
                {
                    this.SetAttributeValue("type", null);
                }
                else
                {
                    this.SetAttributeValue("type", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("Type");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uidata")]
        public string UIData
        {
            get
            {
                return this.GetAttributeValue<string>("uidata");
            }
        }

        /// <summary>
        /// Type of the UI Flow process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uiflowtype")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.workflow_uiflowtype> UIFlowType
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("uiflowtype");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.workflow_uiflowtype)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.workflow_uiflowtype), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("UIFlowType");
                if ((value == null))
                {
                    this.SetAttributeValue("uiflowtype", null);
                }
                else
                {
                    this.SetAttributeValue("uiflowtype", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("UIFlowType");
            }
        }

        /// <summary>
        /// Unique name of the process
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniquename")]
        public string UniqueName
        {
            get
            {
                return this.GetAttributeValue<string>("uniquename");
            }
            set
            {
                this.OnPropertyChanging("UniqueName");
                this.SetAttributeValue("uniquename", value);
                this.OnPropertyChanged("UniqueName");
            }
        }

        /// <summary>
        /// Select the stage a process will be triggered on update.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("updatestage")]
        public Microsoft.Xrm.Sdk.OptionSetValue UpdateStage
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("updatestage");
            }
            set
            {
                this.OnPropertyChanging("UpdateStage");
                this.SetAttributeValue("updatestage", value);
                this.OnPropertyChanged("UpdateStage");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// Unique identifier of the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowid")]
        public System.Nullable<System.Guid> WorkflowId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("workflowid");
            }
            set
            {
                this.OnPropertyChanging("WorkflowId");
                this.SetAttributeValue("workflowid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("WorkflowId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.WorkflowId = value;
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowidunique")]
        public System.Nullable<System.Guid> WorkflowIdUnique
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("workflowidunique");
            }
        }

        /// <summary>
        /// XAML that defines the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("xaml")]
        public string Xaml
        {
            get
            {
                return this.GetAttributeValue<string>("xaml");
            }
            set
            {
                this.OnPropertyChanging("Xaml");
                this.SetAttributeValue("xaml", value);
                this.OnPropertyChanged("Xaml");
            }
        }

        /// <summary>
        /// 1:N workflow_active_workflow
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
        public System.Collections.Generic.IEnumerable<AutoCoE.Extensibility.Plugins.DataModel.Workflow> Referencedworkflow_active_workflow
        {
            get
            {
                return this.GetRelatedEntities<AutoCoE.Extensibility.Plugins.DataModel.Workflow>("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced);
            }
            set
            {
                this.OnPropertyChanging("Referencedworkflow_active_workflow");
                this.SetRelatedEntities<AutoCoE.Extensibility.Plugins.DataModel.Workflow>("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
                this.OnPropertyChanged("Referencedworkflow_active_workflow");
            }
        }

        /// <summary>
        /// 1:N workflow_parent_workflow
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
        public System.Collections.Generic.IEnumerable<AutoCoE.Extensibility.Plugins.DataModel.Workflow> Referencedworkflow_parent_workflow
        {
            get
            {
                return this.GetRelatedEntities<AutoCoE.Extensibility.Plugins.DataModel.Workflow>("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced);
            }
            set
            {
                this.OnPropertyChanging("Referencedworkflow_parent_workflow");
                this.SetRelatedEntities<AutoCoE.Extensibility.Plugins.DataModel.Workflow>("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
                this.OnPropertyChanged("Referencedworkflow_parent_workflow");
            }
        }

        /// <summary>
        /// N:1 workflow_active_workflow
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activeworkflowid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
        public AutoCoE.Extensibility.Plugins.DataModel.Workflow Referencingworkflow_active_workflow
        {
            get
            {
                return this.GetRelatedEntity<AutoCoE.Extensibility.Plugins.DataModel.Workflow>("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referencing);
            }
        }

        /// <summary>
        /// N:1 workflow_parent_workflow
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentworkflowid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
        public AutoCoE.Extensibility.Plugins.DataModel.Workflow Referencingworkflow_parent_workflow
        {
            get
            {
                return this.GetRelatedEntity<AutoCoE.Extensibility.Plugins.DataModel.Workflow>("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referencing);
            }
        }
    }
}
