name = "Microsoft Learning"
license = "MIT"
licenselink = "https://github.com/MicrosoftLearning/Jekyll-Theme/blob/master/LICENSE"
description = "A Hugo adaptation of the Microsoft Learn templare"
homepage = "https://github.com/MicrosoftLearning/Jekyll-Theme"
tags = ["responsive", "one page", "light", "onepage", "company", "clean", "learn"]
features = []
min_version = "0.45"

[author]
  name = "Grant Archibald"
  homepage = "https://github.com/Grant-Archibald-MS"
