//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationkitModules.ApplicationInsightsLogger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomationkitModules.ApplicationInsightsLogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log exception in Application Insights.
        /// </summary>
        internal static string Action1_Description {
            get {
                return ResourceManager.GetString("Action1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogError.
        /// </summary>
        internal static string Action1_FriendlyName {
            get {
                return ResourceManager.GetString("Action1_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of InputArgument.
        /// </summary>
        internal static string Action1_InputArgument1_Description {
            get {
                return ResourceManager.GetString("Action1_InputArgument1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Argument.
        /// </summary>
        internal static string Action1_InputArgument1_FriendlyName {
            get {
                return ResourceManager.GetString("Action1_InputArgument1_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of OutputArgument.
        /// </summary>
        internal static string Action1_OutputArgument1_Description {
            get {
                return ResourceManager.GetString("Action1_OutputArgument1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Argument.
        /// </summary>
        internal static string Action1_OutputArgument1_FriendlyName {
            get {
                return ResourceManager.GetString("Action1_OutputArgument1_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of Action 1.
        /// </summary>
        internal static string Action1_Summary {
            get {
                return ResourceManager.GetString("Action1_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of ApplicationInsightsLogger.
        /// </summary>
        internal static string ApplicationInsightsLogger_Description {
            get {
                return ResourceManager.GetString("ApplicationInsightsLogger_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name of ApplicationInsightsLogger.
        /// </summary>
        internal static string ApplicationInsightsLogger_FriendlyName {
            get {
                return ResourceManager.GetString("ApplicationInsightsLogger_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of ActionError.
        /// </summary>
        internal static string Error_ActionError_Description {
            get {
                return ResourceManager.GetString("Error_ActionError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name of ActionError.
        /// </summary>
        internal static string Error_ActionError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_ActionError_FriendlyName", resourceCulture);
            }
        }
    }
}
