# Get Signing key template for:
# - Read value from Environment variable
# - Convert Base64 into file
stages:
- stage: get_key_stage
  displayName: 'Get Key' 
  jobs:
  - job: get_key
    timeoutInMinutes: 0
    pool: 
      vmImage: 'windows-2022'
    steps:
    - pwsh: |
        $envVariable = "SigningKey"
        Write-Host "Signing Key - "$(SigningKey)
        $64bitData="BwACAAAAAAAAACQAAAAAAFIAUwBBADIAAAAEAAAAAAABAAAAAQAAAHUAEQAgIKAASwBvAN4AxQBBALEAzwDFAN4AUQAYIBQAYwAXAHgApwCiAPsAOAAdIBQgVQAZIHoANADeALsAvgAtAAEAJwBLAFgAvwAlACAAWQBMABog/AAcIAkAuAAOAPcAYQDmAE8AOQAUII0ABQBUABUAFCD8AJAA1QA5ID4AaQCgAKAAUQD7AM4AZQA0APsA6QD8AO0ANQA6AFMABwDlADIAXAAtALEA+AB2ANwAGiAgACIhagA+AEAAbwBfAK4AMCBHAH0BVgC0AEEAcABhATgAeAEeAM4AvgDiAC8AOiAUIBgAMAAXAMUAFADWALcA0wD1APEAZwCNAH4AsABvAEMAdAD/AN0AQABGADgA9QDUANAAZQDVAKwgZwCzABgg2gAVABEA3QCBAEYAfQHOADQASADkACQA/AAzAEkARwBAAPkADwC6ANcAwAAWANwAIiE5IGMAQwAdIOIA9QCNAHkAxAAPACEgrwDLABkgOSC2AHgArgBsAPAASgDbAFsA9wD+ABwg+wA3AK8AJAAgALAA2QBKAMcAHAAzAC4AZwA5AOEA7wABAO0AYQFSAKYAGSAgAC4AIQBvAKUAzQCqANwA4QBsAAsAEgAFAOkAUQBIAMwAVAChAKAArAAeIPYAFwApAMcA0gBPAK4ACADNAMcAxwChAHQAoQAJAM4AJwAeIGsA6ADOACYAXADOAAcAugAOAPUAsQCnAD0AxAB+AD4AUgHmAKMAvgBaAPEAvgDVABQA3gCrAFUAIiDZAL8AdwBMAJIBfADnANUAHSDzAFYAoACkANMAOSDYAHMA7gBsAOIAIwBdAG4AvQCdAHEAewDsALwAnQBlAEYAKwC1AK0AKgAqABoA7wC2AGUAeAAMAAYAcACxAB4A6wC2AF8AeABDABYA3wDZABYAsgA3AM0AbgBrAEoA/gAkADIAcgA8AHgB/QDtADogEgA/AFMBHQDhAGMAjQC0AGwAFCCqALkAaADFACEgKQD/AKwAuwB0ANAAyQASAEgAYQA+AHUA4gC8AOEAMAB1AOEA4ADHABsArQAPAGcAywABAM4ADgCrAO8A7gDLAM0AuwDrAGYAbQAgAGgACAA1AFMBOgBnAKEA/QAdILkAQgDoANEAHgAFAD8AtwB+AQEALADIAG4AUwEZIC8AYQHzANYA3ALnAO0AsgAuAHQA3gB/AJAAWQA2AHYAMwAtAAAAjwBSABggrQA8ACgARADGABogJABGAMIA2gDSAMAAzQCtAPwAEgCNAAwA8QAeACUARwBOANIAawCgACYA0gAwAOYAICCuABwAwwBxADcAkAB3APsAZACiADYALQBWAPQABQA9AMQAWQACAMAAyAAwIBAAjwDiAEQAwAATIDkAZgBlAN8A2AAhICAAFCCmAAIAnQCzAN0AHgBIAP0ADgARADAAaADSAPgAOSDKADkAwwCtAOIAfADtAB0gZQCzAMAA8QB+ANEA7gBkALYAAQACANkAeAHVABgANQAmACEgcgC9AA8A3wCgAMYArQBmAOUA1wBGAA=="
        $filename = "$(Build.SourcesDirectory)\powercat-automation-kit\AutomationCoESatellite\Plugins\autocoe-plugins-master\Plugins\AutoCoEPluginKey.snk"
        if ( $64bitData -ne $NULL ) {  
        $bytes = [Convert]::FromBase64String($64bitData)        
        Add-Content -Path $filename -Value $bytes      
        write-host "SNK file created successfully at $filename"
        }
        else
        {
        write-host "SigningKey Environment variable is not found. Please verify once"
        }
      displayName: 'Signing Key'