# Get Signing key template for:
# - Read value from Environment variable
# - Convert Base64 into file
stages:
- stage: get_key_stage
  displayName: 'Get Key' 
  jobs:
  - job: get_key
    timeoutInMinutes: 0
    pool: 
      vmImage: 'windows-2022'
    steps:
    - pwsh: |
      displayName: 'Signing Key'