//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationKIT_Satellite {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class AutomationKit_Satellite : global::System.Configuration.ApplicationSettingsBase {
        
        private static AutomationKit_Satellite defaultInstance = ((AutomationKit_Satellite)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AutomationKit_Satellite())));
        
        public static AutomationKit_Satellite Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Administrator")]
        public string Const_SysAdmin_Security_Role {
            get {
                return ((string)(this["Const_SysAdmin_Security_Role"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dynamics365")]
        public string Const_Azure_Default_Folder_Name {
            get {
                return ((string)(this["Const_Azure_Default_Folder_Name"]));
            }
        }
    }
}
