//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Microsoft Power Platform Tools")]
[assembly: AssemblyDescription("Microsoft Power Platform Tools for Visual Studio")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0000.1")]
[assembly: AssemblyInformationalVersion("0.1.0000.1+gd485dc2")]
[assembly: AssemblyCopyright("© 2022 Microsoft Corporation. All rights reserved")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("bcc334af-d2d9-430b-a587-3c3d07335a44")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]