//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationKIT_Main {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class AutomationKit_Main : global::System.Configuration.ApplicationSettingsBase {
        
        private static AutomationKit_Main defaultInstance = ((AutomationKit_Main)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AutomationKit_Main())));
        
        public static AutomationKit_Main Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Automation Project - Approvals")]
        public string Flow_Name_Project_Approvals {
            get {
                return ((string)(this["Flow_Name_Project_Approvals"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calculate ROI Saving Potential for Automation Project")]
        public string Flow_Name_Calculate_ROI {
            get {
                return ((string)(this["Flow_Name_Calculate_ROI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sync Environments")]
        public string Flow_Name_Sync_Environments {
            get {
                return ((string)(this["Flow_Name_Sync_Environments"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Automation Project Admin")]
        public string Security_Role_Project_Admin {
            get {
                return ((string)(this["Security_Role_Project_Admin"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Automation Project Contributor")]
        public string Security_Role_Project_Contributor {
            get {
                return ((string)(this["Security_Role_Project_Contributor"]));
            }
            set {
                this["Security_Role_Project_Contributor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Automation Project Viewer")]
        public string Security_Role_Project_Viewer {
            get {
                return ((string)(this["Security_Role_Project_Viewer"]));
            }
            set {
                this["Security_Role_Project_Viewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("administrator@contoso.onmicrosoft.com")]
        public string Administrator_EmailId {
            get {
                return ((string)(this["Administrator_EmailId"]));
            }
            set {
                this["Administrator_EmailId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Automation Project")]
        public string Canvas_App_Project_Name {
            get {
                return ((string)(this["Canvas_App_Project_Name"]));
            }
            set {
                this["Canvas_App_Project_Name"] = value;
            }
        }
    }
}
