//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace AutoCoE.Extensibility.Plugins.DataModel
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum autocoe_FlowSessionLogState
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public enum autocoe_flowsessionlog_statuscode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }

    /// <summary>
    /// 
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("autocoe_flowsessionlog")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public partial class autocoe_FlowSessionLog : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {

        /// <summary>
        /// Default Constructor.
        /// </summary>
        public autocoe_FlowSessionLog() :
                base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "autocoe_flowsessionlog";

        public const string EntityLogicalCollectionName = "autocoe_flowsessionlogs";

        public const string EntitySetName = "autocoe_flowsessionlogs";

        public const int EntityTypeCode = 10320;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_actioninput")]
        public string autocoe_ActionInput
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_actioninput");
            }
            set
            {
                this.OnPropertyChanging("autocoe_ActionInput");
                this.SetAttributeValue("autocoe_actioninput", value);
                this.OnPropertyChanged("autocoe_ActionInput");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_actionoutput")]
        public string autocoe_ActionOutput
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_actionoutput");
            }
            set
            {
                this.OnPropertyChanging("autocoe_ActionOutput");
                this.SetAttributeValue("autocoe_actionoutput", value);
                this.OnPropertyChanged("autocoe_ActionOutput");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_automationowner")]
        public string autocoe_AutomationOwner
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_automationowner");
            }
            set
            {
                this.OnPropertyChanging("autocoe_AutomationOwner");
                this.SetAttributeValue("autocoe_automationowner", value);
                this.OnPropertyChanged("autocoe_AutomationOwner");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_automationowneremail")]
        public string autocoe_AutomationOwnerEmail
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_automationowneremail");
            }
            set
            {
                this.OnPropertyChanging("autocoe_AutomationOwnerEmail");
                this.SetAttributeValue("autocoe_automationowneremail", value);
                this.OnPropertyChanged("autocoe_AutomationOwnerEmail");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowcompletiondate")]
        public System.Nullable<System.DateTime> autocoe_CloudFlowCompletionDate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("autocoe_cloudflowcompletiondate");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowCompletionDate");
                this.SetAttributeValue("autocoe_cloudflowcompletiondate", value);
                this.OnPropertyChanged("autocoe_CloudFlowCompletionDate");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowerrorcode")]
        public string autocoe_CloudFlowErrorCode
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowerrorcode");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowErrorCode");
                this.SetAttributeValue("autocoe_cloudflowerrorcode", value);
                this.OnPropertyChanged("autocoe_CloudFlowErrorCode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowerrordescription")]
        public string autocoe_CloudFlowErrorDescription
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowerrordescription");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowErrorDescription");
                this.SetAttributeValue("autocoe_cloudflowerrordescription", value);
                this.OnPropertyChanged("autocoe_CloudFlowErrorDescription");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowerrorremediationdetails")]
        public string autocoe_CloudFlowErrorRemediationDetails
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowerrorremediationdetails");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowErrorRemediationDetails");
                this.SetAttributeValue("autocoe_cloudflowerrorremediationdetails", value);
                this.OnPropertyChanged("autocoe_CloudFlowErrorRemediationDetails");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowerrorremediationtype")]
        public string autocoe_CloudFlowErrorRemediationType
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowerrorremediationtype");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowErrorRemediationType");
                this.SetAttributeValue("autocoe_cloudflowerrorremediationtype", value);
                this.OnPropertyChanged("autocoe_CloudFlowErrorRemediationType");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowerrorsubject")]
        public string autocoe_CloudFlowErrorSubject
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowerrorsubject");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowErrorSubject");
                this.SetAttributeValue("autocoe_cloudflowerrorsubject", value);
                this.OnPropertyChanged("autocoe_CloudFlowErrorSubject");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowid")]
        public string autocoe_CloudFlowId
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowId");
                this.SetAttributeValue("autocoe_cloudflowid", value);
                this.OnPropertyChanged("autocoe_CloudFlowId");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowname")]
        public string autocoe_CloudFlowName
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowname");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowName");
                this.SetAttributeValue("autocoe_cloudflowname", value);
                this.OnPropertyChanged("autocoe_CloudFlowName");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowresubmiturl")]
        public string autocoe_CloudFlowResubmitURL
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowresubmiturl");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowResubmitURL");
                this.SetAttributeValue("autocoe_cloudflowresubmiturl", value);
                this.OnPropertyChanged("autocoe_CloudFlowResubmitURL");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowrunid")]
        public string autocoe_CloudFlowRunId
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowrunid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowRunId");
                this.SetAttributeValue("autocoe_cloudflowrunid", value);
                this.OnPropertyChanged("autocoe_CloudFlowRunId");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowstartdate")]
        public System.Nullable<System.DateTime> autocoe_CloudFlowStartDate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("autocoe_cloudflowstartdate");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowStartDate");
                this.SetAttributeValue("autocoe_cloudflowstartdate", value);
                this.OnPropertyChanged("autocoe_CloudFlowStartDate");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_cloudflowstatus")]
        public string autocoe_CloudFlowStatus
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_cloudflowstatus");
            }
            set
            {
                this.OnPropertyChanging("autocoe_CloudFlowStatus");
                this.SetAttributeValue("autocoe_cloudflowstatus", value);
                this.OnPropertyChanged("autocoe_CloudFlowStatus");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowactionerrorcode")]
        public string autocoe_DesktopFlowActionErrorCode
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_desktopflowactionerrorcode");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowActionErrorCode");
                this.SetAttributeValue("autocoe_desktopflowactionerrorcode", value);
                this.OnPropertyChanged("autocoe_DesktopFlowActionErrorCode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowactionerrormessage")]
        public string autocoe_DesktopFlowActionErrorMessage
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_desktopflowactionerrormessage");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowActionErrorMessage");
                this.SetAttributeValue("autocoe_desktopflowactionerrormessage", value);
                this.OnPropertyChanged("autocoe_DesktopFlowActionErrorMessage");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowcompletiondate")]
        public System.Nullable<System.DateTime> autocoe_DesktopFlowCompletionDate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("autocoe_desktopflowcompletiondate");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowCompletionDate");
                this.SetAttributeValue("autocoe_desktopflowcompletiondate", value);
                this.OnPropertyChanged("autocoe_DesktopFlowCompletionDate");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowid")]
        public string autocoe_DesktopFlowId
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_desktopflowid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowId");
                this.SetAttributeValue("autocoe_desktopflowid", value);
                this.OnPropertyChanged("autocoe_DesktopFlowId");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowname")]
        public string autocoe_DesktopFlowName
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_desktopflowname");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowName");
                this.SetAttributeValue("autocoe_desktopflowname", value);
                this.OnPropertyChanged("autocoe_DesktopFlowName");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowstartdate")]
        public System.Nullable<System.DateTime> autocoe_DesktopFlowStartDate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("autocoe_desktopflowstartdate");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowStartDate");
                this.SetAttributeValue("autocoe_desktopflowstartdate", value);
                this.OnPropertyChanged("autocoe_DesktopFlowStartDate");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_desktopflowstatus")]
        public string autocoe_DesktopFlowStatus
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_desktopflowstatus");
            }
            set
            {
                this.OnPropertyChanging("autocoe_DesktopFlowStatus");
                this.SetAttributeValue("autocoe_desktopflowstatus", value);
                this.OnPropertyChanged("autocoe_DesktopFlowStatus");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_environmentbaseurl")]
        public string autocoe_EnvironmentBaseURL
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_environmentbaseurl");
            }
            set
            {
                this.OnPropertyChanging("autocoe_EnvironmentBaseURL");
                this.SetAttributeValue("autocoe_environmentbaseurl", value);
                this.OnPropertyChanged("autocoe_EnvironmentBaseURL");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_environmentid")]
        public string autocoe_EnvironmentId
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_environmentid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_EnvironmentId");
                this.SetAttributeValue("autocoe_environmentid", value);
                this.OnPropertyChanged("autocoe_EnvironmentId");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_environmentinstanceurl")]
        public string autocoe_EnvironmentInstanceURL
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_environmentinstanceurl");
            }
            set
            {
                this.OnPropertyChanging("autocoe_EnvironmentInstanceURL");
                this.SetAttributeValue("autocoe_environmentinstanceurl", value);
                this.OnPropertyChanged("autocoe_EnvironmentInstanceURL");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_environmentname")]
        public string autocoe_EnvironmentName
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_environmentname");
            }
            set
            {
                this.OnPropertyChanging("autocoe_EnvironmentName");
                this.SetAttributeValue("autocoe_environmentname", value);
                this.OnPropertyChanged("autocoe_EnvironmentName");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_environmentuniquename")]
        public string autocoe_EnvironmentUniqueName
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_environmentuniquename");
            }
            set
            {
                this.OnPropertyChanging("autocoe_EnvironmentUniqueName");
                this.SetAttributeValue("autocoe_environmentuniquename", value);
                this.OnPropertyChanged("autocoe_EnvironmentUniqueName");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_failingdesktopflowaction")]
        public string autocoe_FailingDesktopFlowAction
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_failingdesktopflowaction");
            }
            set
            {
                this.OnPropertyChanging("autocoe_FailingDesktopFlowAction");
                this.SetAttributeValue("autocoe_failingdesktopflowaction", value);
                this.OnPropertyChanged("autocoe_FailingDesktopFlowAction");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_failingdesktopflowfunction")]
        public string autocoe_FailingDesktopFlowFunction
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_failingdesktopflowfunction");
            }
            set
            {
                this.OnPropertyChanging("autocoe_FailingDesktopFlowFunction");
                this.SetAttributeValue("autocoe_failingdesktopflowfunction", value);
                this.OnPropertyChanged("autocoe_FailingDesktopFlowFunction");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_failingdesktopflowmodule")]
        public string autocoe_FailingDesktopFlowModule
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_failingdesktopflowmodule");
            }
            set
            {
                this.OnPropertyChanging("autocoe_FailingDesktopFlowModule");
                this.SetAttributeValue("autocoe_failingdesktopflowmodule", value);
                this.OnPropertyChanged("autocoe_FailingDesktopFlowModule");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_flowsessionid")]
        public string autocoe_FlowSessionId
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_flowsessionid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_FlowSessionId");
                this.SetAttributeValue("autocoe_flowsessionid", value);
                this.OnPropertyChanged("autocoe_FlowSessionId");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_flowsessionlogid")]
        public System.Nullable<System.Guid> autocoe_FlowSessionLogId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("autocoe_flowsessionlogid");
            }
            set
            {
                this.OnPropertyChanging("autocoe_FlowSessionLogId");
                this.SetAttributeValue("autocoe_flowsessionlogid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("autocoe_FlowSessionLogId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_flowsessionlogid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.autocoe_FlowSessionLogId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_hostname")]
        public string autocoe_Hostname
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_hostname");
            }
            set
            {
                this.OnPropertyChanging("autocoe_Hostname");
                this.SetAttributeValue("autocoe_hostname", value);
                this.OnPropertyChanged("autocoe_Hostname");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_runmode")]
        public string autocoe_RunMode
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_runmode");
            }
            set
            {
                this.OnPropertyChanging("autocoe_RunMode");
                this.SetAttributeValue("autocoe_runmode", value);
                this.OnPropertyChanged("autocoe_RunMode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocoe_trigger")]
        public string autocoe_Trigger
        {
            get
            {
                return this.GetAttributeValue<string>("autocoe_trigger");
            }
            set
            {
                this.OnPropertyChanging("autocoe_Trigger");
                this.SetAttributeValue("autocoe_trigger", value);
                this.OnPropertyChanged("autocoe_Trigger");
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.OnPropertyChanging("OverriddenCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }
            set
            {
                this.OnPropertyChanging("OwnerId");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the Flow Session Log
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.autocoe_FlowSessionLogState> statecode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.autocoe_FlowSessionLogState)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.autocoe_FlowSessionLogState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("statecode");
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Reason for the status of the Flow Session Log
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public System.Nullable<AutoCoE.Extensibility.Plugins.DataModel.autocoe_flowsessionlog_statuscode> statuscode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
                if ((optionSet != null))
                {
                    return ((AutoCoE.Extensibility.Plugins.DataModel.autocoe_flowsessionlog_statuscode)(System.Enum.ToObject(typeof(AutoCoE.Extensibility.Plugins.DataModel.autocoe_flowsessionlog_statuscode), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPropertyChanging("statuscode");
                if ((value == null))
                {
                    this.SetAttributeValue("statuscode", null);
                }
                else
                {
                    this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("statuscode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.OnPropertyChanging("TimeZoneRuleVersionNumber");
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.OnPropertyChanging("UTCConversionTimeZoneCode");
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }
    }

    /// <summary>
    /// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
    public partial class OrganizationServiceContext1 : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
    {

        /// <summary>
        /// Constructor.
        /// </summary>
        public OrganizationServiceContext1(Microsoft.Xrm.Sdk.IOrganizationService service) :
                base(service)
        {
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="AutoCoE.Extensibility.Plugins.DataModel.autocoe_FlowSessionLog"/> entities.
        /// </summary>
        public System.Linq.IQueryable<AutoCoE.Extensibility.Plugins.DataModel.autocoe_FlowSessionLog> autocoe_FlowSessionLogSet
        {
            get
            {
                return this.CreateQuery<AutoCoE.Extensibility.Plugins.DataModel.autocoe_FlowSessionLog>();
            }
        }
    }
}
